apiVersion: 1

datasources:
  - name: Postgres-Heartbeats
    uid: PDCB3A44A6A9A013A
    type: postgres
    access: proxy
    url: postgres:5432
    database: heartbeat_db
    user: heartbeat_user
    secureJsonData:
      password: heartbeat_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
